### ISSUE TITLE
xpath not correct

### ISSUE THREAD

**Issue by AvikantSrivastava** [rizwansoaib/whatsapp-monitor#22]
Please Wait Starting whatsapp-monitor
QR Code Generating
Traceback (most recent call last):
  File "./monitor+log.py", line 37, in <module>
    file.write(driver.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/div[1]/div/div[2]/div/canvas').screenshot_as_png)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div/div[2]/div[1]/div/div[2]/div/canvas"}
  (Session info: headless chrome=80.0.3987.149)

**Comment by AvikantSrivastava** [comment]
I tried tweaking the python script myself : )
Nice project!
